services:
  db:
    image: postgres
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
  web:
    build: ./ipl
    image: ipl:latest
    volumes:
      - ./ipl:/usr/src/app
    depends_on:
      - db
    ports:
      - "8080:8080"
    command: "./wait-for-it.sh db:5432 -- python3 manage.py runserver 0:8080"
    environment:
      - DJANGO_ENV=dev
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@domain.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    depends_on:
      - db
    ports:
      - "80"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
