[pytest]
DJANGO_SETTINGS_MODULE = ipl.settings
django_find_project = true
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = --cov=ipl --cov-report=term-missing --cov-report=html -v
