[pytest]
DJANGO_SETTINGS_MODULE = test_settings
python_files = test_*.py *_test.py *_tests.py
python_classes = Test*
python_functions = test_*
addopts = --cov=ipl --cov-report=term-missing --cov-report=xml -v --reuse-db
django_find_project = true
pythonpath = ipl

[tool:pytest]
DJANGO_SETTINGS_MODULE = test_settings
